// The Pages Function shipped to Cloudflare. Generated at build time with the
// role list and password hashes baked in. Validates session cookies, redirects
// to /login on a missing/expired cookie, and rewrites every request to the
// matching `_variants/<role>/` path before letting Pages serve it.

export interface AuthTemplateConfig {
  /** ordered low → high */
  roles: string[];
  /** role → encoded password hash ("iter:saltHex:hashHex"); only for roles above the default. */
  rolePasswords: Record<string, string>;
  /**
   * Optional Patreon overlay. When present, the Function adds a
   * /auth/patreon/start + /auth/patreon/callback flow that issues the
   * same session cookie as password login. The login page also gains a
   * "Sign in with Patreon" button. Independent of password auth: a role
   * can have either, both, or just a password.
   */
  patreon?: {
    clientId: string;
    campaignId: string;
    /** role name → Patreon tier ID (numeric string) */
    tiers: Record<string, string>;
  };
}

export function renderAuthMiddleware(cfg: AuthTemplateConfig): string {
  const rolesLiteral = JSON.stringify(cfg.roles);
  const passwordsLiteral = JSON.stringify(cfg.rolePasswords);
  const patreonLiteral = JSON.stringify(cfg.patreon ?? null);

  return `// Auto-generated by the vaults CLI. Do not edit by hand.
// Roles, password hashes, and routing live here so the deployed Function
// is fully self-contained and doesn't need any other binding besides
// SESSION_SECRET (set via wrangler secret). When Patreon is configured,
// PATREON_CLIENT_SECRET also has to be set as a Wrangler secret.

const ROLES = ${rolesLiteral};
const PASSWORDS = ${passwordsLiteral};
const PATREON = ${patreonLiteral};
const COOKIE_NAME = "vault_role";
// Non-HttpOnly companion cookie carrying the role name only; the auth check
// uses COOKIE_NAME (which is signed and HttpOnly), this one is purely for UI.
const DISPLAY_COOKIE_NAME = "vault_role_display";
const COOKIE_MAX_AGE = 60 * 60 * 24 * 7; // 7 days
// Bearer tokens (used by Foundry, MCP clients) get a much longer lifetime
// since refreshing means reopening a browser-based approval flow.
const BEARER_MAX_AGE = 60 * 60 * 24 * 90; // 90 days
const PBKDF2_DEFAULT_ITERATIONS = 100000;
// Same shape as a real PBKDF2 hash (iterations:saltHex:hashHex with the
// expected lengths) but with all-zero salt + hash. Used to keep the
// /login response time consistent when the role doesn't exist or has no
// password — running PBKDF2 against this dummy means an attacker can't
// distinguish "role exists" from "role doesn't exist" by timing.
const DUMMY_PASSWORD_HASH = "100000:" + "0".repeat(32) + ":" + "0".repeat(64);

// ── Public middleware entry ────────────────────────────────────────────────

export const onRequest = async (ctx) => {
  const { request, env, next } = ctx;
  const url = new URL(request.url);

  // CORS preflight. Foundry, the MCP server, and AI tooling fetch the
  // manifest / source / search endpoints from a different origin with an
  // 'Authorization: Bearer' header, which triggers a preflight OPTIONS.
  // Allow * because the resource is gated by the bearer token, not by
  // the origin (and we don't want to maintain an allowlist).
  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders() });
  }

  // Block direct access to /_variants/<role>/*; those paths exist in storage
  // for the rewrite below, but exposing them would let anyone fetch any
  // variant's manifest, page, or markdown source by guessing the role name.
  if (url.pathname.startsWith("/_variants/")) {
    return withCors(new Response("Not found", { status: 404 }), request);
  }

  // /login. POST validates a password and sets the session cookie. GET
  // serves the static login page from the deploy root; we have to pass it
  // through explicitly because the variant-rewrite below would otherwise
  // try to fetch /_variants/<role>/login (which doesn't exist).
  if (url.pathname === "/login") {
    if (request.method === "POST") return handleLogin(request, env);
    return next();
  }
  if (url.pathname === "/logout") {
    const headers = new Headers({ Location: safeNext(url.searchParams.get("next")) });
    // Emit the cookie-clear in two variants so we delete the cookie
    // regardless of which form was set: the new SameSite=None+Partitioned
    // form (used by current iframes / direct browsing), and the old
    // SameSite=Lax form (in case the cookie predates the partition switch).
    for (const name of [COOKIE_NAME, DISPLAY_COOKIE_NAME]) {
      for (const variant of clearCookieVariants(name)) {
        headers.append("Set-Cookie", variant);
      }
    }
    return new Response(null, { status: 302, headers });
  }

  // /connect. OAuth-style approval flow for Foundry / MCP clients to obtain
  // a long-lived bearer token. GET shows the approval page; POST signs the
  // token and redirects back to the requesting app.
  if (url.pathname === "/connect" && request.method === "GET") {
    return handleConnectGet(request, env);
  }
  if (url.pathname === "/connect/approve" && request.method === "POST") {
    return handleConnectApprove(request, env);
  }

  // /auth/patreon/* — only mounted when the build saw a Patreon config.
  // Issues the same signed session cookie as password login on success;
  // failure paths bounce back to /login with an error param.
  if (PATREON) {
    if (url.pathname === "/auth/patreon/start" && request.method === "GET") {
      return handlePatreonStart(request, env);
    }
    if (url.pathname === "/auth/patreon/callback" && request.method === "GET") {
      return handlePatreonCallback(request, env);
    }
  }

  // /_batch; bulk source fetch for sync clients (Foundry). Body is
  // newline-separated paths under text/plain so the request stays CORS-
  // simple (no preflight per file → no OPTIONS rate-limit). Response is
  // JSON: { files: { path: content }, missing: [path, ...] }.
  if (url.pathname === "/_batch" && request.method === "POST") {
    return withCors(await handleBatch(request, env), request);
  }

  // /_batch-images; bulk *binary* fetch (images, etc). Same input shape as
  // /_batch but each file is base64-encoded so it can ride in JSON. Used by
  // the Foundry image cache so a 300-image sync is a handful of HTTP calls
  // instead of 300 GETs that hit Cloudflare's per-IP rate limit.
  if (url.pathname === "/_batch-images" && request.method === "POST") {
    return withCors(await handleBatchBinary(request, env), request);
  }

  // Skip rewriting for static-asset paths that don't have a per-role variant.
  // Anything outside the variant tree (images, css, login page, search index
  // for the default role on root, etc.) is served as-is by Pages.
  if (isSharedAsset(url.pathname)) return next();

  // Determine the user's role from the session cookie (default = lowest).
  const role = await readRole(request, env);

  // env.ASSETS canonicalizes URLs (strips .html, strips index.html, redirects
  // with 308s); passing those redirects through to the browser would expose
  // the /_variants/<role>/ path, which the guard at the top of this function
  // explicitly blocks. So: rewrite to a clean URL, and if ASSETS still returns
  // a redirect, follow it server-side instead of leaking it to the client.
  const target = "/_variants/" + role + (url.pathname === "/" ? "/" : url.pathname);
  let rewritten = new Request(new URL(target, url.origin).toString(), request);
  let response = await env.ASSETS.fetch(rewritten);
  if (response.status >= 300 && response.status < 400) {
    const location = response.headers.get("Location");
    if (location && location.startsWith("/_variants/")) {
      rewritten = new Request(new URL(location, url.origin).toString(), request);
      response = await env.ASSETS.fetch(rewritten);
    }
  }
  // Replace bare 404s with the variant's styled 404 page so the reader stays
  // inside the site (sidebar, search, sitemap intact). Only HTML navigation
  // requests get the page; asset/API requests get the bare 404 unchanged.
  if (response.status === 404 && wantsHtml(request)) {
    const fallback = await env.ASSETS.fetch(new URL("/_variants/" + role + "/404.html", url.origin).toString());
    if (fallback.ok) {
      return withCors(new Response(await fallback.text(), {
        status: 404,
        headers: { "Content-Type": "text/html; charset=utf-8" },
      }), request);
    }
  }
  return withCors(response, request);
};

// Headers added for cross-origin clients (Foundry module, MCP). Origin: *
// is safe because the resources are gated by bearer token, not by origin.
function corsHeaders() {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
    "Access-Control-Allow-Headers": "Authorization, Content-Type",
    "Access-Control-Max-Age": "86400",
    "Vary": "Origin",
  };
}

function withCors(response, request) {
  if (!request.headers.get("Origin")) return response;
  // Response from env.ASSETS.fetch is immutable; clone before mutating.
  const headers = new Headers(response.headers);
  for (const [k, v] of Object.entries(corsHeaders())) headers.set(k, v);
  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}

function wantsHtml(request) {
  const accept = request.headers.get("Accept") || "";
  return accept.includes("text/html") || accept === "*/*" || accept === "";
}

// ── Login ─────────────────────────────────────────────────────────────────

async function handleLogin(request, env) {
  const form = await request.formData();
  const role = String(form.get("role") || "");
  const password = String(form.get("password") || "");
  const next = safeNext(form.get("next"));

  // Generic "auth_failed" error for both "no such role / no password set"
  // and "wrong password" branches — distinct codes would let an attacker
  // enumerate which roles exist and which have passwords. Constant-time
  // PBKDF2 comparison handles the timing side; this handles the message
  // side. Run verifyPassword against a dummy hash on the no-role branch
  // so the response time profile stays roughly the same.
  const passwordHash = (ROLES.includes(role) && PASSWORDS[role])
    ? PASSWORDS[role]
    : DUMMY_PASSWORD_HASH;
  const ok = await verifyPassword(password, passwordHash);
  if (!ok || !ROLES.includes(role) || !PASSWORDS[role]) {
    return loginRedirect(next, "auth_failed");
  }

  const cookie = await signSessionCookie(role, env.SESSION_SECRET);
  const headers = new Headers({ Location: next });
  headers.append("Set-Cookie", cookie);
  headers.append("Set-Cookie", DISPLAY_COOKIE_NAME + "=" + encodeURIComponent(role)
    + "; Path=/; Secure; SameSite=None; Partitioned; Max-Age=" + COOKIE_MAX_AGE);
  return new Response(null, { status: 302, headers });
}

// Sanitise a 'next' redirect target. Only same-origin relative paths are
// allowed; anything else (absolute URLs, protocol-relative '//evil.com',
// the protected /_variants/ tree) is replaced with '/'. Prevents the login
// and logout endpoints from being weaponised as open redirects.
function safeNext(value) {
  const s = typeof value === "string" ? value : "";
  if (!s.startsWith("/")) return "/";
  if (s.startsWith("//")) return "/";
  if (s.startsWith("/_variants/")) return "/";
  return s;
}

function loginRedirect(next, error) {
  const url = "/login.html?error=" + encodeURIComponent(error) + "&next=" + encodeURIComponent(next);
  return new Response(null, { status: 302, headers: { Location: url } });
}

// ── Batch source fetch ────────────────────────────────────────────────────
//
// Bulk-read endpoint used by sync clients to avoid making one HTTP request
// per .md file. The body is newline-separated paths (text/plain, so the
// request stays CORS-simple; no preflight). The handler resolves each
// path against the caller's role variant and bundles the results into a
// single JSON response.
//
// Caps:
//   - max 200 paths per call (cap concurrent ASSETS reads inside the worker)
//   - paths must not contain '..' or query/fragment, must not start with '_'
//     (would escape the variant or hit metadata files)

const BATCH_MAX_PATHS = 200;
// Smaller cap for binary; base64 inflates ~4/3x and we don't want to
// blow the worker response budget. ~30 images at 200KB avg ≈ 8MB JSON.
const BATCH_BINARY_MAX_PATHS = 30;

async function handleBatch(request, env) {
  return handleBatchInner(request, env, BATCH_MAX_PATHS, async (res) => res.text());
}

async function handleBatchBinary(request, env) {
  return handleBatchInner(request, env, BATCH_BINARY_MAX_PATHS, async (res) => {
    return base64Encode(new Uint8Array(await res.arrayBuffer()));
  });
}

async function handleBatchInner(request, env, maxPaths, encode) {
  const role = await readRole(request, env);
  if (!ROLES.includes(role)) return batchError(401, "Unauthorized");

  let body;
  try { body = await request.text(); }
  catch { return batchError(400, "Could not read request body."); }

  const paths = body.split(/\\r?\\n/).map((s) => s.trim()).filter(Boolean);
  if (paths.length === 0) return batchError(400, "No paths in request body.");
  if (paths.length > maxPaths) return batchError(400, "Too many paths (max " + maxPaths + ").");
  for (const p of paths) {
    if (!isSafePath(p)) return batchError(400, "Invalid path: " + p);
  }

  // ASSETS.fetch is internal to the worker, so fan-out is cheap.
  const url = new URL(request.url);
  const entries = await Promise.all(paths.map(async (p) => {
    const target = new URL("/_variants/" + role + "/" + encodeVariantPath(p), url.origin).toString();
    const res = await env.ASSETS.fetch(target);
    if (!res.ok) return [p, null];
    return [p, await encode(res)];
  }));

  const files = {};
  const missing = [];
  for (const [p, content] of entries) {
    if (content == null) missing.push(p);
    else files[p] = content;
  }
  return new Response(JSON.stringify({ files, missing }), {
    headers: { "Content-Type": "application/json" },
  });
}

function batchError(status, message) {
  return new Response(JSON.stringify({ error: message }), {
    status, headers: { "Content-Type": "application/json" },
  });
}

function base64Encode(bytes) {
  // btoa wants a binary string. Build it in chunks so we don't blow the
  // call-stack on String.fromCharCode for big payloads.
  let binary = "";
  const CHUNK = 0x8000;
  for (let i = 0; i < bytes.length; i += CHUNK) {
    binary += String.fromCharCode.apply(null, bytes.subarray(i, i + CHUNK));
  }
  return btoa(binary);
}

function isSafePath(p) {
  if (!p || p.length > 1024) return false;
  if (p.includes("..") || p.includes("?") || p.includes("#")) return false;
  if (p.startsWith("/") || p.startsWith("_")) return false;
  // Reject control chars / bare backslashes.
  if (/[\\x00-\\x1f]/.test(p) || p.includes("\\\\")) return false;
  return true;
}

function encodeVariantPath(p) {
  // Each segment is URI-encoded so spaces / unicode round-trip cleanly.
  return p.split("/").map(encodeURIComponent).join("/");
}

// ── Connect (OAuth-style bearer token issuance) ──────────────────────────

async function handleConnectGet(request, env) {
  const url = new URL(request.url);
  const returnTo = url.searchParams.get("return_to") || "";
  const app = url.searchParams.get("app") || "an external app";
  const state = url.searchParams.get("state") || "";
  const delivery = url.searchParams.get("delivery") === "copy" ? "copy" : "redirect";

  // The "redirect" delivery mode (legacy iframe/popup flow) round-trips a
  // token to a host app via return_to. The "copy" delivery mode is the
  // GitHub-CLI-style device flow: the user copy-pastes the token themselves,
  // so return_to is irrelevant and Patreon login works because we're never
  // inside an iframe.
  if (delivery === "redirect" && (!returnTo || !isValidReturnTo(returnTo))) {
    return new Response("Invalid or missing return_to. Must be an http(s) URL.", { status: 400 });
  }

  // Require login first; the user's role is what we're authorising.
  const role = await readRole(request, env);
  const isLoggedIn = role !== ROLES[0] || PASSWORDS[role] != null;
  if (!isLoggedIn || role === ROLES[0]) {
    // Default role; redirect to login first, come back here on success.
    const next = url.pathname + url.search;
    return new Response(null, {
      status: 302,
      headers: { Location: "/login.html?next=" + encodeURIComponent(next) },
    });
  }

  const returnHost = delivery === "copy" ? "" : (() => {
    try { return new URL(returnTo).host; } catch { return returnTo; }
  })();
  const html = renderApprovePage({ app, role, returnTo, returnHost, state, delivery });
  return new Response(html, { headers: { "Content-Type": "text/html; charset=utf-8" } });
}

async function handleConnectApprove(request, env) {
  const form = await request.formData();
  const returnTo = String(form.get("return_to") || "");
  const state = String(form.get("state") || "");
  const delivery = String(form.get("delivery") || "") === "copy" ? "copy" : "redirect";
  const app = String(form.get("app") || "an external app");

  if (delivery === "redirect" && (!returnTo || !isValidReturnTo(returnTo))) {
    return new Response("Invalid return_to.", { status: 400 });
  }
  const role = await readRole(request, env);
  if (role === ROLES[0]) {
    // User is anonymous; reject (shouldn't reach here via normal UI flow).
    return new Response("Not signed in.", { status: 401 });
  }

  const token = await signToken(role, env.SESSION_SECRET, BEARER_MAX_AGE);
  const html = delivery === "copy"
    ? renderConnectCopyPage({ token, role, app })
    // Legacy delivery: postMessage to parent/opener; falls back to top-
    // level redirect with the token in the query string. Kept for any
    // existing iframe-based clients; new clients should use delivery=copy.
    : renderConnectDeliveryPage({ token, state, returnTo });
  return new Response(html, { headers: { "Content-Type": "text/html; charset=utf-8" } });
}

function renderConnectDeliveryPage({ token, state, returnTo }) {
  const returnOrigin = (() => { try { return new URL(returnTo).origin; } catch { return ""; } })();
  const tokenAttr = escAttr(token);
  const stateAttr = escAttr(state);
  const originAttr = escAttr(returnOrigin);
  const returnAttr = escAttr(returnTo);
  return \`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Connecting…</title>
<link rel="stylesheet" href="/styles.css">
<style>
  body { display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; font-family: inherit; }
  .card { max-width: 24rem; padding: 2rem; text-align: center; color: var(--muted); }
  .card h1 { margin: 0 0 0.5rem; font-size: 1.1rem; color: var(--fg); }
  .card a { color: var(--accent); }
</style>
</head>
<body>
<div class="card">
  <h1>Authorising…</h1>
  <p id="status">You can close this window.</p>
  <p><a id="manual" href="#">Continue manually</a> if it doesn't close on its own.</p>
</div>
<script>
(function () {
  var token = "\${tokenAttr}";
  var state = "\${stateAttr}";
  var origin = "\${originAttr}";
  var returnTo = "\${returnAttr}";

  // Iframe flow: parent window is the host (Foundry inside DialogV2).
  // Popup flow: opener is the host. In both cases we postMessage to the
  // host's origin (not '*') so the token can't be intercepted by anything
  // else with a window reference.
  var target = null;
  if (window.parent && window.parent !== window) target = window.parent;
  else if (window.opener && !window.opener.closed) target = window.opener;
  if (target && origin) {
    try {
      target.postMessage({ type: "vaults-connect", token: token, state: state }, origin);
      // Popup self-closes; iframe is dismissed by the host on receipt.
      if (target === window.opener) { try { window.close(); } catch (e) {} }
      return;
    } catch (e) { /* fall through to redirect */ }
  }

  // No parent or opener; fall back to the original redirect flow.
  var sep = returnTo.indexOf("?") === -1 ? "?" : "&";
  var target = returnTo + sep + "token=" + encodeURIComponent(token)
    + (state ? "&state=" + encodeURIComponent(state) : "");
  document.getElementById("manual").href = target;
  document.getElementById("status").textContent = "Redirecting back…";
  window.location.replace(target);
})();
</script>
</body>
</html>\`;
}

function isValidReturnTo(s) {
  try {
    const u = new URL(s);
    return u.protocol === "http:" || u.protocol === "https:";
  } catch { return false; }
}

function renderApprovePage({ app, role, returnTo, returnHost, state, delivery }) {
  const escapedApp = escHtml(app);
  const escapedRole = escHtml(role);
  const escapedHost = escHtml(returnHost);
  const escapedReturnTo = escAttr(returnTo);
  const escapedState = escAttr(state);
  const escapedDelivery = escAttr(delivery);
  const escapedAppAttr = escAttr(app);
  const isCopy = delivery === "copy";
  return \`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Authorize \${escapedApp}</title>
<link rel="stylesheet" href="/styles.css">
<style>
  body { display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }
  .approve-card {
    max-width: 28rem; width: 90%; padding: 2rem;
    border: 1px solid var(--rule); border-radius: 6px; background: var(--bg);
  }
  .approve-card h1 { margin: 0 0 1rem; font-size: 1.4rem; }
  .approve-card .info { color: var(--muted); font-size: 0.9rem; margin: 0 0 0.75rem; }
  .approve-card .info strong { color: var(--accent); }
  .approve-card .return-host {
    display: block; margin: 0.75rem 0 1.25rem;
    padding: 0.5rem 0.75rem; background: var(--wikilink-bg);
    border: 1px solid var(--rule); border-radius: 4px;
    font-family: ui-monospace, monospace; font-size: 0.85rem;
    word-break: break-all;
  }
  .approve-card .actions { display: flex; gap: 0.75rem; margin-top: 1.25rem; }
  .approve-card button, .approve-card .deny {
    flex: 1; padding: 0.55rem 1rem; font: inherit; font-size: 0.95rem;
    border: 1px solid var(--rule); border-radius: 4px; cursor: pointer;
    text-align: center; text-decoration: none;
  }
  .approve-card button { background: var(--accent); color: var(--accent-fg); border-color: var(--accent); }
  .approve-card .deny { background: var(--bg); color: var(--muted); }
  .approve-card .warning { color: #b94a3a; font-size: 0.78rem; margin-top: 1rem; }
</style>
</head>
<body>
<form class="approve-card" method="POST" action="/connect/approve">
  <h1>Authorize \${escapedApp}</h1>
  <p class="info">
    <strong>\${escapedApp}</strong> wants access to your vault as
    <strong>\${escapedRole}</strong>.
  </p>
  \${isCopy
    ? \`<p class="info">After approval, this page will display a token to copy and paste back into <strong>\${escapedApp}</strong>.</p>\`
    : \`<p class="info">After approval, you'll be redirected to:</p>
       <code class="return-host">\${escapedHost}</code>
       <p class="warning">⚠ Verify the destination above looks right. If you didn't initiate this request, click Deny.</p>\`}
  <input type="hidden" name="return_to" value="\${escapedReturnTo}">
  <input type="hidden" name="state" value="\${escapedState}">
  <input type="hidden" name="delivery" value="\${escapedDelivery}">
  <input type="hidden" name="app" value="\${escapedAppAttr}">
  <div class="actions">
    <a class="deny" href="/">Deny</a>
    <button type="submit">Approve</button>
  </div>
</form>
</body>
</html>\`;
}

function renderConnectCopyPage({ token, role, app }) {
  const escapedApp = escHtml(app);
  const escapedRole = escHtml(role);
  const escapedToken = escAttr(token);
  return \`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Authorised \${escapedApp}</title>
<link rel="stylesheet" href="/styles.css">
<style>
  body { display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }
  .copy-card {
    max-width: 32rem; width: 90%; padding: 2rem;
    border: 1px solid var(--rule); border-radius: 6px; background: var(--bg);
  }
  .copy-card h1 { margin: 0 0 0.75rem; font-size: 1.3rem; }
  .copy-card .info { color: var(--muted); font-size: 0.9rem; margin: 0 0 0.75rem; }
  .copy-card .info strong { color: var(--accent); }
  .copy-card .token {
    display: block; width: 100%; box-sizing: border-box;
    margin: 0.75rem 0;
    padding: 0.75rem 0.85rem;
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size: 0.82rem; line-height: 1.45;
    background: var(--wikilink-bg);
    color: var(--fg);
    border: 1px solid var(--rule); border-radius: 4px;
    word-break: break-all; resize: vertical;
  }
  .copy-card .copy-btn {
    width: 100%; padding: 0.6rem 1rem; margin-top: 0.5rem; font: inherit; font-size: 0.95rem;
    background: var(--accent); color: var(--accent-fg); border: 0; border-radius: 4px; cursor: pointer;
  }
  .copy-card .copy-status {
    text-align: center; color: var(--muted); font-size: 0.78rem; margin-top: 0.5rem; min-height: 1em;
  }
  .copy-card .copy-status.ok { color: #2a8b58; }
  .copy-card ol { font-size: 0.88rem; color: var(--muted); padding-left: 1.25rem; margin: 0.75rem 0 0; }
  .copy-card ol li { margin: 0.25rem 0; }
</style>
</head>
<body>
<div class="copy-card">
  <h1>✓ Authorised \${escapedApp}</h1>
  <p class="info">
    A token for the <strong>\${escapedRole}</strong> tier has been generated.
    Copy it back into <strong>\${escapedApp}</strong> to complete sign-in.
  </p>
  <textarea class="token" id="token" readonly rows="4" onclick="this.select()">\${escapedToken}</textarea>
  <button type="button" class="copy-btn" id="copy-btn">Copy token</button>
  <p class="copy-status" id="copy-status"></p>
  <ol>
    <li>Click <strong>Copy token</strong> above.</li>
    <li>Switch back to \${escapedApp}.</li>
    <li>Paste into the token field and confirm.</li>
  </ol>
</div>
<script>
(function () {
  var btn = document.getElementById('copy-btn');
  var ta = document.getElementById('token');
  var status = document.getElementById('copy-status');
  btn.addEventListener('click', async function () {
    try {
      await navigator.clipboard.writeText(ta.value);
      status.textContent = 'Copied to clipboard.';
      status.className = 'copy-status ok';
    } catch (e) {
      ta.select();
      status.textContent = 'Press Ctrl/Cmd-C to copy.';
      status.className = 'copy-status';
    }
    setTimeout(function () { status.textContent = ''; }, 4000);
  });
})();
</script>
</body>
</html>\`;
}

function escHtml(s) { return String(s).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c])); }
function escAttr(s) { return String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }

// ── Patreon OAuth (optional, additive to password login) ─────────────────
// Bound only when PATREON !== null (i.e. the build saw a configured
// patreon block with at least one role mapped to a tier). Issues the same
// signed session cookie as password login on success; bounces back to
// /login with an error param on failure. CSRF state rides through a short-
// lived signed cookie so the callback can verify the round-trip.

const PATREON_STATE_COOKIE = "vault_patreon_state";
const PATREON_STATE_TTL = 600; // 10 minutes — long enough for the user to authorise

async function handlePatreonStart(request, env) {
  if (!env.PATREON_CLIENT_SECRET) {
    return new Response("Patreon login is misconfigured: PATREON_CLIENT_SECRET secret is missing.", { status: 500 });
  }
  const url = new URL(request.url);
  const next = safeNext(url.searchParams.get("next"));
  // Bind state to next so a forged callback can't drop the user on an
  // attacker-chosen URL post-login. The signed cookie carries both back.
  const stateValue = crypto.randomUUID();
  const stateCookie = await signStateCookie({ state: stateValue, next }, env.SESSION_SECRET);

  const redirectUri = url.origin + "/auth/patreon/callback";
  const authorize = new URL("https://www.patreon.com/oauth2/authorize");
  authorize.searchParams.set("response_type", "code");
  authorize.searchParams.set("client_id", PATREON.clientId);
  authorize.searchParams.set("redirect_uri", redirectUri);
  authorize.searchParams.set("scope", "identity identity.memberships");
  authorize.searchParams.set("state", stateValue);

  const headers = new Headers({ Location: authorize.toString() });
  headers.append("Set-Cookie", stateCookie);
  return new Response(null, { status: 302, headers });
}

async function handlePatreonCallback(request, env) {
  if (!env.PATREON_CLIENT_SECRET) {
    return loginRedirect("/", "patreon_misconfigured");
  }
  const url = new URL(request.url);
  const code = url.searchParams.get("code");
  const state = url.searchParams.get("state");
  if (!code || !state) return loginRedirect("/", "patreon_failed");

  const stateData = await readStateCookie(request, env.SESSION_SECRET);
  // Always clear the state cookie regardless of outcome.
  const clearState = clearCookieVariants(PATREON_STATE_COOKIE);

  if (!stateData || stateData.state !== state) {
    const headers = new Headers({ Location: "/login?error=patreon_state_mismatch" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }
  const next = stateData.next || "/";

  // Exchange code → access token. The token is short-lived; we don't store
  // it. Only used once, immediately, to look up the visitor's memberships.
  let access;
  try {
    access = await patreonExchangeCode(code, url.origin + "/auth/patreon/callback", env.PATREON_CLIENT_SECRET);
  } catch (err) {
    console.warn("Patreon token exchange failed:", err);
    const headers = new Headers({ Location: "/login?error=patreon_token_exchange" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  let identity;
  try { identity = await patreonFetchIdentity(access); }
  catch (err) {
    console.warn("Patreon identity fetch failed:", err);
    const headers = new Headers({ Location: "/login?error=patreon_identity" });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  const role = matchHighestRole(identity, PATREON.campaignId, PATREON.tiers);
  if (!role) {
    // Authenticated, but no qualifying tier on this campaign. Send them
    // back to /login with a specific error so the UI can explain.
    const headers = new Headers({ Location: "/login?error=patreon_no_tier&next=" + encodeURIComponent(next) });
    for (const v of clearState) headers.append("Set-Cookie", v);
    return new Response(null, { status: 302, headers });
  }

  const cookie = await signSessionCookie(role, env.SESSION_SECRET);
  const headers = new Headers({ Location: next });
  headers.append("Set-Cookie", cookie);
  headers.append("Set-Cookie", DISPLAY_COOKIE_NAME + "=" + encodeURIComponent(role)
    + "; Path=/; Secure; SameSite=None; Partitioned; Max-Age=" + COOKIE_MAX_AGE);
  for (const v of clearState) headers.append("Set-Cookie", v);
  return new Response(null, { status: 302, headers });
}

/**
 * Walk the visitor's identity payload, find memberships scoped to OUR
 * campaign, and return the highest-ranked role whose mapped tier ID
 * appears in the visitor's currently-entitled tiers. Returns null if no
 * tier matches — the visitor may be a patron of someone else, or the
 * creator's own account, or just not entitled to any mapped tier.
 */
function matchHighestRole(identity, campaignId, tiers) {
  const memberships = (identity?.included || []).filter((it) => it.type === "member");
  // Filter to memberships on our campaign (Patreon nests campaign under relationships).
  const ourCampaignMemberships = memberships.filter((m) => {
    const camp = m.relationships?.campaign?.data;
    return camp && camp.type === "campaign" && String(camp.id) === String(campaignId);
  });
  const entitledTierIds = new Set();
  for (const m of ourCampaignMemberships) {
    const ents = m.relationships?.currently_entitled_tiers?.data || [];
    for (const t of ents) if (t.type === "tier") entitledTierIds.add(String(t.id));
  }
  if (entitledTierIds.size === 0) return null;
  // Roles are ordered low → high; iterate from highest to find the best match.
  for (let i = ROLES.length - 1; i >= 0; i--) {
    const r = ROLES[i];
    const tier = tiers[r];
    if (tier && entitledTierIds.has(String(tier))) return r;
  }
  return null;
}

async function patreonExchangeCode(code, redirectUri, clientSecret) {
  const body = new URLSearchParams({
    grant_type: "authorization_code",
    code,
    client_id: PATREON.clientId,
    client_secret: clientSecret,
    redirect_uri: redirectUri,
  });
  const res = await fetch("https://www.patreon.com/api/oauth2/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: body.toString(),
  });
  if (!res.ok) throw new Error("token exchange status " + res.status);
  const data = await res.json();
  if (!data.access_token) throw new Error("no access_token in response");
  return data.access_token;
}

async function patreonFetchIdentity(accessToken) {
  // We need the visitor's memberships AND, for each membership, which tiers
  // they're currently entitled to. Patreon's JSON:API include syntax pulls
  // both into one round-trip.
  const url = new URL("https://www.patreon.com/api/oauth2/v2/identity");
  url.searchParams.set("include", "memberships,memberships.currently_entitled_tiers,memberships.campaign");
  url.searchParams.set("fields[member]", "patron_status");
  const res = await fetch(url.toString(), {
    headers: { Authorization: "Bearer " + accessToken },
  });
  if (!res.ok) throw new Error("identity status " + res.status);
  return await res.json();
}

// State cookie: stores { state, next } signed with SESSION_SECRET, used to
// verify the OAuth callback came from our /start handler and not a forgery.
// Lifetime is short (PATREON_STATE_TTL); kept distinct from the long-lived
// session cookie so a stolen state cookie can't impersonate a session.

async function signStateCookie(payload, secret) {
  const exp = Math.floor(Date.now() / 1000) + PATREON_STATE_TTL;
  const data = JSON.stringify({ ...payload, exp });
  const sig = await hmac(data, secret);
  const value = btoa(data) + "." + sig;
  return PATREON_STATE_COOKIE + "=" + value
    + "; Path=/; Secure; SameSite=Lax; HttpOnly; Max-Age=" + PATREON_STATE_TTL;
}

async function readStateCookie(request, secret) {
  const cookies = parseCookie(request.headers.get("Cookie") || "");
  const raw = cookies[PATREON_STATE_COOKIE];
  if (!raw) return null;
  const dot = raw.lastIndexOf(".");
  if (dot < 0) return null;
  const dataB64 = raw.slice(0, dot);
  const sig = raw.slice(dot + 1);
  let data;
  try { data = atob(dataB64); }
  catch { return null; }
  const expected = await hmac(data, secret);
  if (sig !== expected) return null;
  let parsed;
  try { parsed = JSON.parse(data); }
  catch { return null; }
  if (!parsed || typeof parsed.exp !== "number" || parsed.exp < Math.floor(Date.now() / 1000)) return null;
  return parsed;
}

// ── Cookie + role lookup ──────────────────────────────────────────────────

async function readRole(request, env) {
  const fallback = ROLES[0];
  if (!env.SESSION_SECRET) return fallback;

  // Authorization: Bearer <token>; used by curl / the MCP server / any
  // client that can set request headers freely. Same signed-token format
  // as the cookie, so verification is shared.
  const auth = request.headers.get("Authorization") || "";
  const bearerMatch = /^Bearer\\s+(.+)$/i.exec(auth);
  if (bearerMatch) {
    const role = await verifyToken(bearerMatch[1], env.SESSION_SECRET);
    if (role && ROLES.includes(role)) return role;
  }

  // ?_token=<token>; used by the Foundry module so cross-origin GETs stay
  // CORS-simple and don't trigger a preflight per file (Cloudflare rate-
  // limits OPTIONS bursts and a sync is hundreds of unique URLs).
  const queryToken = new URL(request.url).searchParams.get("_token");
  if (queryToken) {
    const role = await verifyToken(queryToken, env.SESSION_SECRET);
    if (role && ROLES.includes(role)) return role;
  }

  const cookie = parseCookie(request.headers.get("Cookie") || "")[COOKIE_NAME];
  if (!cookie) return fallback;
  const role = await verifyToken(cookie, env.SESSION_SECRET);
  return role && ROLES.includes(role) ? role : fallback;
}

// Format: <role>.<expiryUnix>.<hmacHex>
async function signToken(role, secret, maxAgeSeconds) {
  const exp = Math.floor(Date.now() / 1000) + maxAgeSeconds;
  const payload = role + "." + exp;
  const sig = await hmac(payload, secret);
  return payload + "." + sig;
}

async function signSessionCookie(role, secret) {
  const value = await signToken(role, secret, COOKIE_MAX_AGE);
  // SameSite=None + Partitioned (CHIPS); required so the cookie persists
  // when the vault is loaded inside a cross-origin iframe (the Foundry
  // connect dialog). Partitioned scopes the cookie per parent origin, so
  // it isn't a general third-party tracking cookie. Top-level browsing
  // still works normally.
  return COOKIE_NAME + "=" + value
    + "; Path=/; HttpOnly; Secure; SameSite=None; Partitioned; Max-Age=" + COOKIE_MAX_AGE;
}

async function verifyToken(token, secret) {
  const parts = token.split(".");
  if (parts.length !== 3) return null;
  const [role, expStr, sig] = parts;
  const exp = Number(expStr);
  if (!Number.isFinite(exp) || exp < Math.floor(Date.now() / 1000)) return null;
  const expected = await hmac(role + "." + expStr, secret);
  return constantTimeEqual(sig, expected) ? role : null;
}

function clearCookieVariants(name) {
  // Browsers match cookies for deletion on (Path, Domain, Secure, SameSite,
  // Partitioned). A single Set-Cookie attempt only matches one configuration,
  // so we emit two; one that matches cookies set by the current
  // (SameSite=None+Partitioned) signSessionCookie, and one that matches the
  // older Lax form. Both are safe to send; the unmatched one is a no-op.
  const httpOnly = name === COOKIE_NAME ? "HttpOnly; " : "";
  return [
    name + "=; Path=/; " + httpOnly + "Secure; SameSite=None; Partitioned; Max-Age=0",
    name + "=; Path=/; " + httpOnly + "Secure; SameSite=Lax; Max-Age=0",
  ];
}

// ── Crypto primitives (Web Crypto API) ────────────────────────────────────

async function hmac(message, secretHex) {
  const keyBytes = fromHex(secretHex);
  const key = await crypto.subtle.importKey(
    "raw", keyBytes, { name: "HMAC", hash: "SHA-256" }, false, ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message));
  return toHex(new Uint8Array(sig));
}

async function verifyPassword(password, encoded) {
  const parts = encoded.split(":");
  if (parts.length !== 3) return false;
  const iterations = Number(parts[0]) || PBKDF2_DEFAULT_ITERATIONS;
  const salt = fromHex(parts[1]);
  const expected = fromHex(parts[2]);
  const key = await crypto.subtle.importKey(
    "raw", new TextEncoder().encode(password), { name: "PBKDF2" }, false, ["deriveBits"],
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, hash: "SHA-256", iterations },
    key, expected.length * 8,
  );
  return constantTimeEqual(toHex(new Uint8Array(bits)), toHex(expected));
}

function constantTimeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

function toHex(bytes) {
  let s = "";
  for (let i = 0; i < bytes.length; i++) s += bytes[i].toString(16).padStart(2, "0");
  return s;
}

function fromHex(hex) {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

function parseCookie(header) {
  const out = {};
  for (const part of header.split(/;\\s*/)) {
    const eq = part.indexOf("=");
    if (eq > 0) out[part.slice(0, eq)] = part.slice(eq + 1);
  }
  return out;
}

function isSharedAsset(pathname) {
  // Allowlist of root-served files that are intentionally public to every
  // visitor (no role gate). Everything else — including images, .body.html
  // fragments, .preview.json, the search index — goes through the variant
  // rewrite so role-restricted content is structurally unreachable on
  // under-tier deploys.
  //
  // SYNCHRONISATION POINT: every file the build writes to the deploy
  // ROOT (vs. into _variants/<role>/) must be listed here, otherwise it
  // 404s for every visitor. Build code that places root-level files:
  //   - styles.css / user.css        — build.ts (writeFile join(outputDir, ...))
  //   - login.html                   — build.ts (multi-role only)
  //   - favicon.ico                  — build.ts (buildFavicon)
  //   - functions/_middleware.js     — build.ts (multi-role only; not served)
  // If you add another, add it both here AND in build.ts.
  if (pathname === "/styles.css") return true;
  if (pathname === "/user.css") return true;
  if (pathname === "/login.html") return true;
  if (pathname === "/favicon.ico" || pathname === "/favicon.svg") return true;
  if (pathname === "/robots.txt") return true;
  return false;
}
`;
}

export const LOGIN_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sign in</title>
<link rel="stylesheet" href="/styles.css">
<style>
  body { display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }
  .login-card {
    max-width: 24rem; width: 90%; padding: 2rem;
    border: 1px solid var(--rule); border-radius: 6px; background: var(--bg);
  }
  .login-card h1 { margin: 0 0 1rem; font-size: 1.4rem; }
  .login-card label { display: block; font-size: 0.85rem; color: var(--muted); margin: 0.75rem 0 0.25rem; }
  .login-card select, .login-card input[type=password] {
    width: 100%; padding: 0.5rem 0.65rem; font: inherit; font-size: 0.95rem;
    background: var(--bg); color: var(--fg);
    border: 1px solid var(--rule); border-radius: 4px; outline: none;
  }
  .login-card select:focus, .login-card input:focus { border-color: var(--accent); box-shadow: 0 0 0 2px var(--wikilink-bg); }
  .login-card button {
    width: 100%; padding: 0.55rem 1rem; margin-top: 1rem; font: inherit;
    background: var(--accent); color: var(--accent-fg); border: 0; border-radius: 4px; cursor: pointer;
  }
  .login-error { color: #b94a3a; font-size: 0.85rem; margin: 0.75rem 0 0; }
  .login-divider {
    display: flex; align-items: center; gap: 0.6rem;
    margin: 1.25rem 0 1rem;
    font-size: 0.78rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.06em;
  }
  .login-divider::before, .login-divider::after {
    content: ""; flex: 1; height: 1px; background: var(--rule);
  }
  .patreon-btn {
    display: flex; align-items: center; justify-content: center; gap: 0.5rem;
    width: 100%; padding: 0.55rem 1rem; font: inherit; font-size: 0.95rem;
    background: #ff424d; color: white; border: 0; border-radius: 4px;
    cursor: pointer; text-decoration: none;
  }
  .patreon-btn:hover { filter: brightness(1.05); }
  .patreon-hint { color: var(--muted); font-size: 0.78rem; margin-top: 0.6rem; text-align: center; }
  .patreon-iframe-note {
    color: var(--muted); font-size: 0.78rem; line-height: 1.45;
    margin-top: 0.6rem; padding: 0.6rem 0.7rem;
    border: 1px dashed var(--rule); border-radius: 4px;
  }
</style>
</head>
<body>
<div class="login-card"__PATREON_ROLES_ATTR__>
  <h1>Sign in</h1>
  <p id="err" class="login-error" hidden></p>
  <form method="POST" action="/login">
    <label for="role">Role</label>
    <select id="role" name="role">__ROLE_OPTIONS__</select>
    <label for="password">Password</label>
    <input id="password" type="password" name="password" autocomplete="current-password" required>
    <input type="hidden" name="next" id="next">
    <button type="submit">Sign in</button>
  </form>
  <div id="patreon-section" hidden>
    <div class="login-divider">or</div>
    <a id="patreon-btn" class="patreon-btn" href="#">
      <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
        <circle cx="14.5" cy="9.5" r="6.5"/>
        <rect x="2" y="3" width="3.5" height="18"/>
      </svg>
      Sign in with Patreon
    </a>
    <p class="patreon-hint">
      Active patrons of the configured tiers can sign in directly. The role
      selector above only matters for password sign-in.
    </p>
    <p class="patreon-iframe-note" hidden>
      Patreon refuses to be embedded in iframes, so its sign-in button is
      hidden when this page is loaded in one (e.g. a Foundry connect
      dialog). Use a password here, or open the wiki in a normal browser
      tab to sign in with Patreon.
    </p>
  </div>
</div>
<script>
  const params = new URLSearchParams(location.search);
  const next = params.get("next") || "/";
  document.getElementById("next").value = next;
  const err = params.get("error");
  if (err) {
    const el = document.getElementById("err");
    const messages = {
      // Single message for any password-path failure — distinct error
      // codes would let an attacker enumerate which roles exist.
      auth_failed: "Invalid role or password.",
      patreon_state_mismatch: "Patreon sign-in expired or was tampered with. Please try again.",
      patreon_token_exchange: "Couldn't exchange the Patreon authorisation. Try again.",
      patreon_identity: "Patreon authenticated but we couldn't load your tier information.",
      patreon_no_tier: "Signed in to Patreon, but your current pledge doesn't grant any of the configured tiers.",
      patreon_misconfigured: "Patreon login is misconfigured for this deploy.",
      patreon_failed: "Patreon sign-in failed.",
    };
    el.textContent = messages[err] || "Sign-in failed.";
    el.hidden = false;
  }
  // Show the Patreon button only if the build emitted a roles list for it
  // (i.e. patreon is configured AND at least one role has a tier mapping).
  // The Foundry module's connect flow now uses delivery=copy (paste-token),
  // not an iframe, so Patreon's X-Frame-Options is no longer a problem in
  // the supported flow. The iframe-detection note still fires defensively
  // for any third-party that embeds /login.html directly.
  const card = document.querySelector(".login-card");
  if (card.dataset.patreonRoles) {
    const section = document.getElementById("patreon-section");
    section.hidden = false;
    const inIframe = window.parent !== window;
    if (inIframe) {
      document.getElementById("patreon-btn").hidden = true;
      document.querySelector(".patreon-hint").hidden = true;
      document.querySelector(".patreon-iframe-note").hidden = false;
    } else {
      document.getElementById("patreon-btn").href = "/auth/patreon/start?next=" + encodeURIComponent(next);
    }
  }
  // Autofocus moved here so it picks the right field whether the password
  // form is visible or the user is going for the Patreon button.
  const pwd = document.getElementById("password");
  if (pwd && !err) pwd.focus();
</script>
</body>
</html>`;
